'use strict';function DeltaTimer(b,d){function e(){var j=+new Date,l=j-h,m=Math.max(d-l,0);f=setTimeout(e,m),h=j+m,b(j)}var f,h;this.start=function(){return f=setTimeout(e,0),h=+new Date,h},this.stop=function(){return clearTimeout(f),h}}var grta={calcScale:function calcScale(b){var d=document.getElementById(b).width,e=$('#'+b).width();return d/e},createGameStatus:function createGameStatus(){var b={lastUpdate:+new Date,score:0,totalTime:30,time:30,
gameStatus:'ready',elements:[]};return b.addElement=function(d){return b.elements.push(d)},b},updateElements:function updateElements(b,d,e){var f=e-b.lastUpdate;'started'===b.gameStatus&&(b.time-=f/1000,0>=b.time&&function(){b.gameStatus='gameOver';var j=b.elements.find(function(m){return m.gameID===b.currentGame});j.on_gameEnd(b),j.score=b.score,j.showCaption=!0,b.currentGame='none';var l=b.elements.find(function(m){return'clock'===m.type});l.rotation=-5,TweenMax.to(l,0.01,{rotation:5,ease:Power0.easeNone,yoyo:!0,repeat:-1}),TweenMax.to(l,0.4,{delay:5,opacity:0,onComplete:function onComplete(){l.remove=!0,b.time=b.totalTime,b.gameStatus='ready',j.tween&&j.tween.pause()}}),$('#'+j.captionID).html(j.postCaption(j)),TweenMax.to('#'+j.captionID,0.4,{opacity:1}),b.score=0}());var h=b.elements.map(function(j){return d.map(function(l){j[l]+=j[l+'Vel']*f,j[l]<j[l+'Limits'][0]?j[l]=j['on_'+l+'LimitLo'](j):j[l]>j[l+'Limits'][1]&&(j[l]=j['on_'+l+'LimitHi'](j)),0===j[l+'Vel']&&j['on_'+l+'VelZero'](j),j[l+'Friction']&&0!=j[l+'Vel']&&(j[l+'Vel']+=j[l+'Friction']*f,!j.frictionHalt&&Math.sign(j[l+'Vel'])==Math.sign(j[l+'Friction'])&&(j[l+'Vel']=0))}),j.aliveLimit&&(j.alive=j.alive>j.aliveLimit?j.on_aliveLimit(j):j.alive+=1),j.isSprite&&(j.currentFrame=Math.floor(e/j.frameDelay%j.frames)),j});
return b.elements=h.filter(function(j){return!0!=j.remove}),b.lastUpdate=e,b},
dashToCamel:function dashToCamel(b){return b.replace(/-([a-z])/g,function(d){return d[1].toUpperCase()})},
preLoadImages:function preLoadImages(b,d){var e=Object.keys(b),f={},h={};e.map(function(j){f[j]=!1,h[j]=new Image,h[j].onload=function(){f[j]=!0,Object.keys(f).reduce(function(l,m){return l&&f[m]})&&d(h)},h[j].src=b[j]})},wrapText:function wrapText(b,d,e,f,h,j){var l=d.split(' '),m='';l.map(function(n,o,q){var r=m+l[o]+' ',t=b.measureText(r),u=t.width;u>h&&0<o?(b.fillText(m,e,f),m=l[o]+' ',f+=j):m=r}),b.fillText(m,e,f)},
giveBorder:function giveBorder(b,d,e,f){var h=document.createElement('canvas');h.width=b.width,h.height=b.height;var j=h.getContext('2d');return[-1,-1,0,-1,1,-1,-1,0,1,0,-1,1,0,1,1,1].map(function(l,m,n){m%2&&j.drawImage(b,n[m]*d,n[m+1]*d)}),j.globalCompositeOperation='source-in',j.fillStyle=e,j.fillRect(0,0,h.width,h.height),j.globalCompositeOperation='source-over',f||j.drawImage(b,0,0),h},
giveStick:function giveStick(b,d,e,f,h,j,l){var m=document.createElement('canvas');Math.sin(j*Math.PI/180)*d,Math.cos(j*Math.PI/180)*d,m.width=b.width,m.height=b.height;var n=m.getContext('2d');return n.save(),n.translate(f,h),n.rotate(j*Math.PI/180),n.lineWidth=e,n.strokeStyle=l,n.beginPath(),n.moveTo(0,0),n.lineTo(d,0),n.stroke(),n.restore(),n.drawImage(b,0,0),m},createElement:function createElement(){return{type:'',render:'main',offScreen:!1,shadow:!1,frictionHalt:!0,image:null,imgHeight:null,imgWidth:null,trueHeight:function trueHeight(b){return b.imgHeight*b.trueScale},trueWidth:function trueWidth(b){return b.imgWidth*b.trueScale},isSprite:!1,frames:1,frameDelay:100,currentFrame:0,frameOffset:function frameOffset(b){return b.currentFrame*b.imgWidth},
xpos:0,xposVel:0,xposFriction:0,xposLimits:[-9999,9999],on_xposLimitLo:function on_xposLimitLo(b){return b.xposLimits[0]},on_xposLimitHi:function on_xposLimitHi(b){return b.xposLimits[1]},on_xposVelZero:function on_xposVelZero(b){return b.xpos},
ypos:0,yposVel:0,yposFriction:0,yposLimits:[-9999,9999],on_yposLimitLo:function on_yposLimitLo(b){return b.yposLimits[0]},on_yposLimitHi:function on_yposLimitHi(b){return b.yposLimits[1]},on_yposVelZero:function on_yposVelZero(b){return b.ypos},slideY:0,
rotation:0,rotationX:0,rotationY:0,rotationVel:0,rotationLimits:[-360,360],rotationFriction:0,on_rotationLimitLo:function on_rotationLimitLo(b){return b.rotationLimits[0]},on_rotationLimitHi:function on_rotationLimitHi(b){return b.rotationLimits[1]},on_rotationVelZero:function on_rotationVelZero(b){return b.rotation},
initialScale:1,scale:1,scaleX:0,scaleY:0,trueScale:function trueScale(b){return b.initialScale*b.scale},scaleVel:0,scaleLimits:[0,2],scaleFriction:0,on_scaleLimitLo:function on_scaleLimitLo(b){return b.scaleLimits[0]},on_scaleLimitHi:function on_scaleLimitHi(b){return b.scaleLimits[1]},on_scaleVelZero:function on_scaleVelZero(b){return b.scale},
opacity:1,opacityVel:0,opacityLimits:[0,1],opacityFriction:0,on_opacityLimitLo:function on_opacityLimitLo(b){return b.opacityLimits[0]},on_opacityLimitHi:function on_opacityLimitHi(b){return b.opacityLimits[1]},on_opacityVelZero:function on_opacityVelZero(b){return b.opacity},alive:0,aliveLimit:0,on_aliveLimit:function on_aliveLimit(b){return b.aliveLimit},clickable:!1,clickAreas:[],hasClicked:function hasClicked(b,d){var e=!1;return b.clickAreas.map(function(f){d.offsetX*scaleFactor>f[0]*b.trueScale(b)+b.xpos&&d.offsetX*scaleFactor<f[2]*b.trueScale(b)+b.xpos&&d.offsetY*scaleFactor>f[1]*b.trueScale(b)+b.ypos&&d.offsetY*scaleFactor<f[3]*b.trueScale(b)+b.ypos&&(e=!0)}),e},on_click:function on_click(b,d){},on_gameEnd:function on_gameEnd(){},
draw:function draw(b,d,e){d.save(),d.globalAlpha=b.opacity;var f=b.xpos+b.rotationX,h=b.ypos+b.rotationY;d.translate(f,h),d.rotate(b.rotation*Math.PI/180),d.translate(-f,-h),d.scale(b.trueScale(b),b.trueScale(b)),d.translate(b.xpos/b.trueScale(b),b.ypos/b.trueScale(b)),d.drawImage(b.image,b.frameOffset(b),0,b.imgWidth,b.imgHeight,0,0,b.imgWidth,b.imgHeight),d.restore()}};
}};
